export default Object.freeze({
  ACTION: 'Action',
  ADVENTURE: 'Adventure',
  ANIMATION: 'Animation',
  COMEDY: 'Comedy',
  CRIME: 'Crime',
  DRAMA: 'Drama',
  FAMILY: 'Family',
  FANTASY: 'Fantasy',
  MUSIC: 'Music',
  MYSTERY: 'Mystery',
  ROMANCE: 'Romance',
  SCI_FI: 'Sci-Fi',
  THRILLER: 'Thriller',
});
